include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_single_quotes
    - sort_pub_dependencies
    - avoid_print
    - avoid_unnecessary_containers
    - sized_box_for_whitespace
    - avoid_empty_else
