name: windows_ime_manager
description: A Flutter plugin for managing Input Method Editors (IME) on Windows, supporting seamless switching between different languages.
version: 1.0.3
homepage: https://github.com/i-aiymen/windows_ime_manager
repository: https://github.com/i-aiymen/windows_ime_manager

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: WindowsImeManagerPluginCApi
